name: Deploy to Server
run: |
    echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
    echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"
    echo "Key length: ${#{{ secrets.SSH_PRIVATE_KEY }}}"
  shell: bash
  env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/olympiad.firm.kiev.ua
            git pull origin main
            yarn install
            yarn run build
