name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Echo secrets (debug)
        run: |
          echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
          echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"
          echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"

          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Версия должна быть либо '20', либо '18'

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 135.181.29.211
          username: zagadum
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/olympiad.firm.kiev.ua
            git pull origin main
            yarn install
            yarn build
